# Generated by Django 4.0.4 on 2022-07-22 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_idea_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.idea')),
            ],
        ),
    ]
