# Generated by Django 4.0.4 on 2022-07-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_progress_progressupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressupdate',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='progressupdate',
            name='date',
            field=models.DateTimeField(verbose_name='Update on:'),
        ),
    ]
